/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: 3eeafd731407841bbc1389da7739c1b7)
// Runtime types generated with workerd@1.20260409.1 2026-04-12 global_fetch_strictly_public,nodejs_compat
declare namespace Cloudflare {
	interface Env {
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		NEXTJS_ENV: string;
		WORKER_SELF_REFERENCE: Fetcher /* chat-agent */;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
